sequenceDiagram
    title Order Service
    participant Client as Client
    participant OrderController as OrderController
    participant OrderService as OrderService
    participant PurchaseService as PurchaseService
    participant InvoiceService as InvoiceService

    Note over Client: POST /orders
    Client->>OrderController: post(payload)
    activate OrderController
    OrderController->>OrderService: create(payload)
    activate OrderService
    Note over OrderService: order = new Order(payload)
    alt order != null
        par Parallel Processing
            OrderService->>PurchaseService: createPO(order)
            activate PurchaseService
            PurchaseService-->>OrderService: 
            deactivate PurchaseService
        and
            OrderService->>InvoiceService: createInvoice(order)
            activate InvoiceService
            InvoiceService-->>OrderService: 
            deactivate InvoiceService
        end
    end
    OrderService-->>OrderController: 
    deactivate OrderService
    OrderController-->>Client: 
    deactivate OrderController
    